== Herbstwolke Deployer

[frame=none, grid=none, caption=, width="75%", cols="^2,^2"]
.Build Status by Branches
#TODO

The Herbstwolke Deployer project defines a Service Provider Interface (SPI) for deploying long lived applications and short lived tasks. It is intended to be a drop-in replacement for https://github.com/spring-attic/spring-cloud-deployer[Spring Cloud Deployer].

== Components

The https://github.com/dcolazin/herbstwolke-deployer/tree/master/herbstwolke-deployer-spi[SPI] project
defines the core interfaces, including https://github.com/dcolazin/herbstwolke-deployer/blob/master/herbstwolke-deployer-spi/src/main/java/org/springframework/cloud/deployer/spi/app/AppDeployer.java[AppDeployer]
and https://github.com/dcolazin/herbstwolke-deployer/blob/master/herbstwolke-deployer-spi/src/main/java/org/springframework/cloud/deployer/spi/task/TaskLauncher.java[TaskLauncher]
as well as the core domain model.

The https://github.com/dcolazin/herbstwolke-deployer/tree/master/herbstwolke-deployer-spi-test[SPI Test] project provides
the basic test framework that any SPI implementation should use to verify its functionality.

The https://github.com/dcolazin/herbstwolke-deployer/tree/master/herbstwolke-deployer-resource-maven[herbstwolke-deployer-resource-maven]
project provides support for referencing Maven artifacts via Spring's `Resource` abstraction.

The https://github.com/dcolazin/herbstwolke-deployer/tree/master/herbstwolke-deployer-resource-docker[herbstwolke-deployer-resource-docker]
project provides support for referencing Docker artifacts via Spring's `Resource` abstraction.

The https://github.com/dcolazin/herbstwolke-deployer/tree/master/herbstwolke-deployer-resource-support[herbstwolke-deployer-resource-support]
project provides various common support classes for working with `Resources`, such as the
https://github.com/dcolazin/herbstwolke-deployer/blob/master/herbstwolke-deployer-resource-support/src/main/java/org/springframework/cloud/deployer/resource/registry/UriRegistry.java[UriRegistry]
for maintaining the locations of app artifacts, and the
https://github.com/dcolazin/herbstwolke-deployer/blob/master/herbstwolke-deployer-resource-support/src/main/java/org/springframework/cloud/deployer/resource/support/DelegatingResourceLoader.java[DelegatingResourceLoader]
for working with multiple `ResourceLoader` implementations in a map with URI schemes as keys.

There is also an implementation of the SPI for running apps locally. That link is provided below along with other SPI implementations.

== Implementations

This deployer SPI has been implemented for several runtime environments. Here are the github locations:

* https://github.com/dcolazin/herbstwolke-deployer/blob/master/herbstwolke-deployer-local[Local]
* https://github.com/dcolazin/herbstwolke-deployer/blob/master/herbstwolke-deployer-cloudfoundry[Cloud Foundry]
* https://github.com/dcolazin/herbstwolke-deployer/blob/master/herbstwolke-deployer-kubernetes[Kubernetes]

=== Building

Clone the repo and type 

----
$ ./mvnw clean install 
----
